// Export Terraform variable values to an Ansible var_file
resource "local_file" "tf_ansible_vars_file_new" {
  content  = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.
    SQL_Server: ${azurerm_mysql_flexible_server.example.fqdn}
    Web_Server: ${azurerm_linux_virtual_machine.DStoeckm-vm.public_ip_address}
    DOC
  filename = "group_vars/tf_ansible_vars_file.yml"
}

// Export Terraform variable values to an Ansible inventory -> Zeile 8     SQL_Server: ${azurerm_mssql_server.example.fqdn}

resource "local_file" "tf_inventory" {
  content  = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.
    [dashboard]
    ${azurerm_linux_virtual_machine.DStoeckm-vm.public_ip_address}
    [dashboard:vars]
    ansible_ssh_private_key_file=/Users/dstoeckm/.ssh/id_azure
    ansible_python_interpreter=/usr/bin/python3


    DOC
  filename = "group_vars/tf_inventory"
}

// Run Ansible playbook to install OpenCart and SQL dump
resource "null_resource" "ansible_deployment" {
  provisioner "local-exec" {
    command = "ansible-playbook -i group_vars/tf_inventory opencart-azure.yml"
  }
  depends_on = [
    local_file.tf_ansible_vars_file_new,
  ]
}
